(()=>{
const DB='PokerHandLoggerStaticDBv2',VER=1;
const ranks=['A','K','Q','J','T','9','8','7','6','5','4','3','2'];
const suits=[{c:'s',m:'♠',k:'black'},{c:'h',m:'♥',k:'red'},{c:'d',m:'♦',k:'red'},{c:'c',m:'♣',k:'black'}];
const positions=['UTG','UTG+1','LJ','HJ','CO','BU','SB','BB'];
const actions=['Open','Call','Fold','FoldR','3bet','Call3','4bet+','Call4+'];
let db,sessions=[],hands=[],currentSessionId=null,selected=[],activeCardSlot=null,editingSessionId=null,editingHandId=null;
const $=id=>document.getElementById(id), uuid=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+Math.random().toString(16).slice(2), today=()=>new Date().toISOString().slice(0,10), dkey=iso=>(iso||new Date().toISOString()).slice(0,10);
function openDb(){return new Promise((res,rej)=>{const r=indexedDB.open(DB,VER);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains('sessions')){let s=d.createObjectStore('sessions',{keyPath:'id'});s.createIndex('date','date');s.createIndex('createdAt','createdAt')}if(!d.objectStoreNames.contains('hands')){let h=d.createObjectStore('hands',{keyPath:'id'});h.createIndex('sessionId','sessionId');h.createIndex('createdAt','createdAt');h.createIndex('dateKey','dateKey')}};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
const store=(n,m='readonly')=>db.transaction(n,m).objectStore(n);
const all=n=>new Promise((res,rej)=>{const r=store(n).getAll();r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error)});
const put=(n,v)=>new Promise((res,rej)=>{const r=store(n,'readwrite').put(v);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)});
const del=(n,id)=>new Promise((res,rej)=>{const r=store(n,'readwrite').delete(id);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)});
function clearHands(sessionId){return new Promise((res,rej)=>{const t=db.transaction('hands','readwrite'),i=t.objectStore('hands').index('sessionId'),r=i.openCursor(IDBKeyRange.only(sessionId));r.onsuccess=()=>{const c=r.result;if(c){c.delete();c.continue()}};t.oncomplete=()=>res();t.onerror=()=>rej(t.error)})}
function deleteSession(sessionId){return new Promise((res,rej)=>{const t=db.transaction(['sessions','hands'],'readwrite');t.objectStore('sessions').delete(sessionId);const r=t.objectStore('hands').index('sessionId').openCursor(IDBKeyRange.only(sessionId));r.onsuccess=()=>{const c=r.result;if(c){c.delete();c.continue()}};t.oncomplete=()=>res();t.onerror=()=>rej(t.error)})}
function clearAll(){return new Promise((res,rej)=>{const t=db.transaction(['sessions','hands'],'readwrite');t.objectStore('sessions').clear();t.objectStore('hands').clear();t.oncomplete=()=>res();t.onerror=()=>rej(t.error)})}
function cardLabel(code){if(!code)return'';if(code==='??')return'??';const s=suits.find(x=>x.c===code[1]);return code[0]+(s?s.m:'')}
function cardColor(code){if(code==='??')return'unknown';return suits.find(x=>x.c===code[1])?.k||'black'}
function sessionTitle(s){return `${s.date}${s.suffix?` ${s.suffix}`:''}`}
function toast(msg){const e=$('toast');e.textContent=msg;e.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.add('hidden'),1600)}
function fillSelects(){const af=$('actionFilter');af.innerHTML='<option value="">すべて</option>';actions.forEach(a=>{af.add(new Option(a,a))});const pf=$('positionFilter');pf.innerHTML='<option value="">すべて</option>';positions.forEach(p=>pf.add(new Option(p,p)));renderPickers()}
function renderPickers(){const pp=$('positionPick'),ap=$('actionPick');if(!pp||!ap)return;const cls=label=>'action-'+label.toLowerCase().replaceAll('+','plus').replaceAll('-','');const make=(box,items,input,features=[],action=false)=>{box.innerHTML='';items.forEach(label=>{const val=label==='未選択'?'':label,b=document.createElement('button');b.type='button';b.className='pickBtn '+(input.value===val?'sel ':'')+(features.includes(label)?'feature ':'')+(action?cls(label):'');b.textContent=label;b.onclick=()=>{input.value=val;renderPickers()};box.appendChild(b)})};make(pp,['未選択',...positions],$('positionInput'));make(ap,['未選択',...actions],$('actionInput'),[],true)}
async function load(){sessions=(await all('sessions')).sort((a,b)=>(b.date||'').localeCompare(a.date||'')||(b.createdAt||'').localeCompare(a.createdAt||''));if(!sessions.length){const s={id:uuid(),date:today(),suffix:'',type:'tournament',note:'',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};await put('sessions',s);sessions=[s]}if(!currentSessionId||!sessions.some(s=>s.id===currentSessionId))currentSessionId=sessions[0].id;hands=(await all('hands')).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));render()}
const cur=()=>sessions.find(s=>s.id===currentSessionId), curHands=()=>hands.filter(h=>h.sessionId===currentSessionId);
function renderSessions(){const sel=$('sessionSelect');sel.innerHTML='';sessions.forEach(s=>sel.add(new Option(sessionTitle(s),s.id)));sel.value=currentSessionId;const s=cur(),c=curHands().length;$('sessionMeta').textContent=s?`${s.type} / ${c} hands${s.note?' / '+s.note:''}`:''}
function chooseCard(code){if(activeCardSlot===null)return;selected[activeCardSlot]=code;if(selected[0]&&selected[1]){activeCardSlot=null}else{activeCardSlot=selected[0]?1:0}renderSelected();renderDeck()}
function renderDeck(){const g=$('deckGrid');g.innerHTML='';if(activeCardSlot===null){g.classList.add('hidden');return}g.classList.remove('hidden');ranks.forEach(r=>suits.forEach(s=>{const code=r+s.c,b=document.createElement('button');b.type='button';b.className='cardBtn '+s.k+(selected[activeCardSlot]===code?' sel':'');b.textContent=r+s.m;b.disabled=selected.some((x,i)=>i!==activeCardSlot&&x===code);b.onclick=()=>chooseCard(code);g.appendChild(b)}));const u=document.createElement('button');u.type='button';u.className='cardBtn unknownCard'+(selected[activeCardSlot]==='??'?' sel':'');u.textContent='Unknown';u.onclick=()=>chooseCard('??');g.appendChild(u)}
function renderSelected(){const e=$('selectedCards');e.innerHTML='';[0,1].forEach(i=>{const c=selected[i],d=document.createElement('button');d.type='button';d.className=(c?'card '+cardColor(c):'empty')+(activeCardSlot===i?' active':'');d.textContent=c?cardLabel(c):(i+1)+'枚目';d.onclick=()=>{activeCardSlot=activeCardSlot===i?null:i;renderSelected();renderDeck()};e.appendChild(d)})}
function filtered(){return curHands().filter(h=>(!$('dateFilter').value||h.dateKey===$('dateFilter').value)&&(!$('positionFilter').value||h.position===$('positionFilter').value)&&(!$('actionFilter').value||h.action===$('actionFilter').value))}
function handKey(h){const a=h.card1,b=h.card2;if(!a||!b||a==='??'||b==='??')return null;const r1=a[0],r2=b[0],i1=ranks.indexOf(r1),i2=ranks.indexOf(r2);if(i1<0||i2<0)return null;if(r1===r2)return r1+r2;const hi=i1<i2?r1:r2,lo=i1<i2?r2:r1,suited=a[1]===b[1];return hi+lo+(suited?'s':'o')}
function matrixLabel(i,j){if(i===j)return ranks[i]+ranks[j];return i<j?ranks[i]+ranks[j]+'s':ranks[j]+ranks[i]+'o'}
function renderHeatmap(){const box=$('handHeatmap');if(!box)return;const rows=filtered(),counts={};rows.forEach(h=>{const k=handKey(h);if(k)counts[k]=(counts[k]||0)+1});const known=Object.values(counts).reduce((a,b)=>a+b,0),max=Math.max(0,...Object.values(counts));box.innerHTML='';const head=document.createElement('div');head.className='heatmapHead';head.innerHTML=`<b>ハンド頻度</b><span>${rows.length} hands / known ${known}</span>`;box.appendChild(head);const grid=document.createElement('div');grid.className='rangeGrid';ranks.forEach((_,i)=>ranks.forEach((_,j)=>{const label=matrixLabel(i,j),n=counts[label]||0,cell=document.createElement('div');cell.className='rangeCell '+(i===j?'pair':(i<j?'suited':'offsuit'))+(n?' hit':'');cell.style.setProperty('--heat',max?String(n/max):'0');cell.innerHTML=`<b>${label}</b><span>${n||''}</span>`;grid.appendChild(cell)}));box.appendChild(grid)}
function renderHistory(){const box=$('historyList'),rows=filtered();box.innerHTML='';if(!rows.length){box.innerHTML='<div class="meta">履歴なし</div>';return}const groups={};rows.forEach(h=>{const s=sessions.find(x=>x.id===h.sessionId)||cur();const k=sessionTitle(s);(groups[k]||(groups[k]={s,items:[]})).items.push(h)});Object.values(groups).forEach(g=>{const sec=document.createElement('div');sec.className='sessionBox';const title=document.createElement('div');title.className='sessionTitle';title.innerHTML=`<div>${sessionTitle(g.s)}</div><span>${g.items.length} hands</span>`;sec.appendChild(title);g.items.forEach(h=>{const row=document.createElement('div');row.className='handRow';row.innerHTML=`<div class="handMini"><span class="mini ${cardColor(h.card1)}">${cardLabel(h.card1)}</span><span class="mini ${cardColor(h.card2)}">${cardLabel(h.card2)}</span></div><div class="handInfo"><b>${h.position||'-'} / ${h.action||'未選択'}</b><span>${new Date(h.createdAt).toLocaleString()}${h.memo?' / '+escapeHtml(h.memo):''}</span></div><div class="handBtns"><button class="btn editHand" data-id="${h.id}">編集</button><button class="btn del" data-id="${h.id}">削除</button></div>`;sec.appendChild(row)});box.appendChild(sec)});box.querySelectorAll('.editHand').forEach(b=>b.onclick=()=>openEditHand(b.dataset.id));box.querySelectorAll('.del').forEach(b=>b.onclick=async()=>{await del('hands',b.dataset.id);await load();toast('削除しました')})}
function renderStats(){const rows=filtered(),grid=$('statsGrid');$('countBadge').textContent=`${rows.length} hands`;grid.innerHTML='';
  const known=rows.filter(h=>h.action);
  const count=a=>known.filter(h=>h.action===a).length;
  const pct=(num,den)=>den?`${((num/den)*100).toFixed(1)}%`:'-';
  const vpipActions=['Open','Call','3bet','Call3','4bet+','Call4+','All-in'];
  const pfrActions=['Open','3bet','4bet+','All-in'];
  const vpip=known.filter(h=>vpipActions.includes(h.action)).length;
  const pfr=known.filter(h=>pfrActions.includes(h.action)).length;
  const threeBetPlus=count('3bet')+count('4bet+')+count('All-in'), threeBetPlusDen=count('Call')+count('3bet')+count('Call3')+count('4bet+')+count('Call4+')+count('All-in');
  const add=(parent,k,v)=>{const d=document.createElement('div');d.className='stat';d.innerHTML=`<b>${v}</b><span>${k}</span>`;parent.appendChild(d)};
  const top=document.createElement('div');top.className='statsRow statsTop';
  add(top,'Total',rows.length);add(top,'VPIP',pct(vpip,known.length));add(top,'PFR',pct(pfr,known.length));add(top,'3bet+%',pct(threeBetPlus,threeBetPlusDen));grid.appendChild(top);
  const bottom=document.createElement('div');bottom.className='statsRow statsActions';
  ['Open','Call','Fold','FoldR','3bet','Call3','4bet+','Call4+'].forEach(a=>add(bottom,a,count(a)));grid.appendChild(bottom)}
function render(){renderSessions();renderSelected();renderDeck();renderHeatmap();renderHistory();renderStats()}
function openSession(edit){editingSessionId=edit?currentSessionId:null;const s=edit?cur():{date:today(),suffix:'',type:'tournament',note:''};$('sessionDialogTitle').textContent=edit?'セッション編集':'新規セッション';$('sessionDateInput').value=s.date||today();$('sessionSuffixInput').value=s.suffix||'';$('sessionTypeInput').value=s.type||'tournament';$('sessionNoteInput').value=s.note||'';$('deleteSessionBtn').classList.toggle('hidden',!edit);$('sessionDialog').showModal()}
async function saveSession(e){e.preventDefault();const old=editingSessionId?sessions.find(s=>s.id===editingSessionId):null,now=new Date().toISOString();const s={id:old?.id||uuid(),date:$('sessionDateInput').value||today(),suffix:$('sessionSuffixInput').value.trim(),type:$('sessionTypeInput').value,note:$('sessionNoteInput').value.trim(),createdAt:old?.createdAt||now,updatedAt:now};await put('sessions',s);currentSessionId=s.id;$('sessionDialog').close();await load();toast('保存しました')}
async function saveHand(){if(!selected[0]||!selected[1])return toast('2枚選択してください');const now=new Date().toISOString();await put('hands',{id:uuid(),sessionId:currentSessionId,card1:selected[0],card2:selected[1],position:$('positionInput').value,action:$('actionInput').value,memo:$('memoInput').value.trim(),createdAt:now,dateKey:dkey(now)});selected=[];activeCardSlot=null;$('memoInput').value='';$('positionInput').value='';$('actionInput').value='';renderPickers();await load();toast('記録しました')}
function cardOptionsHtml(value){const opts=['<option value="??">Unknown</option>'];ranks.forEach(r=>suits.forEach(s=>{const code=r+s.c;opts.push(`<option value="${code}"${code===value?' selected':''}>${cardLabel(code)}</option>`)}));return opts.join('')}
function fillEditSelect(select,items,value,emptyLabel='未選択'){select.innerHTML='';select.add(new Option(emptyLabel,''));items.forEach(x=>select.add(new Option(x,x)));select.value=value||''}
function openEditHand(id){const h=hands.find(x=>x.id===id);if(!h)return;editingHandId=id;$('editCard1Input').innerHTML=cardOptionsHtml(h.card1);$('editCard2Input').innerHTML=cardOptionsHtml(h.card2);$('editCard1Input').value=h.card1||'??';$('editCard2Input').value=h.card2||'??';fillEditSelect($('editPositionInput'),positions,h.position);fillEditSelect($('editActionInput'),actions,h.action);$('editMemoInput').value=h.memo||'';$('editHandDialog').showModal()}
async function saveEditHand(e){e.preventDefault();const h=hands.find(x=>x.id===editingHandId);if(!h)return;const c1=$('editCard1Input').value,c2=$('editCard2Input').value;if(!c1||!c2)return toast('2枚選択してください');if(c1===c2&&c1!=='??')return toast('同じカードは選択できません');await put('hands',{...h,card1:c1,card2:c2,position:$('editPositionInput').value,action:$('editActionInput').value,memo:$('editMemoInput').value.trim(),updatedAt:new Date().toISOString()});$('editHandDialog').close();editingHandId=null;await load();toast('更新しました')}
const csvEsc=v=>'"'+String(v??'').replaceAll('"','""')+'"';
function exportCsv(){const rows=filtered();const head=['sessionDate','sessionSuffix','sessionType','sessionNote','id','createdAt','dateKey','card1','card2','position','action','memo'];const csv=[head.join(',')].concat(rows.map(h=>{const s=sessions.find(x=>x.id===h.sessionId)||cur();return [s.date,s.suffix,s.type,s.note,h.id,h.createdAt,h.dateKey,h.card1,h.card2,h.position,h.action,h.memo].map(csvEsc).join(',')})).join('\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a'),s=cur();a.href=url;a.download=`poker-hands-${sessionTitle(s).replace(/[^a-zA-Z0-9_-]/g,'_')}.csv`;a.click();URL.revokeObjectURL(url)}
function parseCsv(t){const rows=[];let r=[],v='',q=false;for(let i=0;i<t.length;i++){const ch=t[i],nx=t[i+1];if(q){if(ch==='"'&&nx==='"'){v+='"';i++}else if(ch==='"')q=false;else v+=ch}else{if(ch==='"')q=true;else if(ch===','){r.push(v);v=''}else if(ch==='\n'){r.push(v);rows.push(r);r=[];v=''}else if(ch!=='\r')v+=ch}}if(v||r.length){r.push(v);rows.push(r)}return rows}
async function importCsv(file){const rows=parseCsv(await file.text());if(rows.length<2)return toast('CSVにデータがありません');const head=rows[0],idx=k=>head.indexOf(k);let n=0;for(const r of rows.slice(1)){const now=new Date().toISOString(),rec={id:uuid(),sessionId:currentSessionId,card1:r[idx('card1')]||'',card2:r[idx('card2')]||'',position:r[idx('position')]||'',action:r[idx('action')]||'',memo:r[idx('memo')]||'',createdAt:r[idx('createdAt')]||now,dateKey:r[idx('dateKey')]||dkey(now)};if(rec.card1&&rec.card2){await put('hands',rec);n++}}await load();$('importInput').value='';toast(`${n}件取り込みました`)}
function escapeHtml(s){return String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function bind(){fillSelects();$('sessionSelect').onchange=e=>{currentSessionId=e.target.value;render()};$('newSessionBtn').onclick=()=>openSession(false);$('editSessionBtn').onclick=()=>openSession(true);$('saveSessionBtn').onclick=saveSession;$('editHandForm').onsubmit=saveEditHand;$('deleteSessionBtn').onclick=async()=>{if(confirm('このセッションと履歴を削除しますか？')){await deleteSession(currentSessionId);$('sessionDialog').close();await load()}};$('resetCardsBtn').onclick=()=>{selected=[];activeCardSlot=null;renderSelected();renderDeck()};$('saveHandBtn').onclick=saveHand;$('toggleFiltersBtn').onclick=()=>$('filters').classList.toggle('hidden');['dateFilter','positionFilter','actionFilter'].forEach(id=>$(id).onchange=render);$('clearFiltersBtn').onclick=()=>{$('dateFilter').value='';$('positionFilter').value='';$('actionFilter').value='';render()};$('exportBtn').onclick=exportCsv;$('importInput').onchange=e=>e.target.files[0]&&importCsv(e.target.files[0]);$('deleteSessionHandsBtn').onclick=async()=>{if(confirm('現在のセッションの履歴だけ全削除しますか？')){await clearHands(currentSessionId);await load();toast('削除しました')}};$('deleteAllBtn').onclick=async()=>{if(confirm('全セッション・全履歴を削除しますか？')){await clearAll();currentSessionId=null;await load();toast('全削除しました')}};let deferred;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;$('installBtn').classList.remove('hidden')});$('installBtn').onclick=async()=>{if(deferred){deferred.prompt();deferred=null;$('installBtn').classList.add('hidden')}}}
async function sw(){if('serviceWorker'in navigator&&location.protocol!=='file:'){try{await navigator.serviceWorker.register('./service-worker.js')}catch(e){}}}
async function init(){bind();db=await openDb();await load();await sw()}init().catch(e=>{console.error(e);alert('起動に失敗しました: '+e.message)})
})();
